version: "3.0"

services:
  wordpress:
    build:
      context: requirements/wordpress/
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  mariadb:
    build:
      context: requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - inception

  nginx:
    build:
      context: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/learodri/data/wordpress
        
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/learodri/data/mariadb